# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
    #  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
dist: trusty
sudo: required
services:
  - docker
before_install:
  - echo "**** pulling Docker image"
  - docker pull tkpapp/texlive-julia-minimal

before_script:
    - julia -e 'import Pkg; Pkg.build(); Pkg.clone("https://github.com/PieterjanRobbe/SimpleMultigrid.jl.git"); Pkg.clone("https://github.com/PieterjanRobbe/NotSoSimpleMultigrid.jl.git"); Pkg.clone("https://github.com/PieterjanRobbe/LognormalDiffusionProblems.jl.git")'
env:
  - PYTHON=""
script:
  - echo "**** running Docker"
  - docker run --env-file travis_docker_env.list -t -a STDOUT -a STDIN -a STDERR -v $PWD:/mnt tkpapp/texlive-julia-minimal /mnt/travis_docker_test_script.sh $TRAVIS_JULIA_VERSION
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("Reporter")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("Reporter")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
